#!/bin/bash
VERSION=v0.3.0
HELP="midiphonor init script"

if [ -z $1 -o $1 = "-h" -o $1 = "--help" ];then
  echo $HELP

elif [ $1 = "version" -o $1 = "v" -o $1 = "-v" ]; then
  echo $VERSION

elif [ $1 = "init" ]; then
  shift
  docker run -it -v $(pwd):/app -w /app node yarn install

elif [ $1 = "dev" -o $1 = "d" ]; then
  shift
  docker run -it -v $(pwd):/app -w /app -p 1234:1234 node yarn parcel src/index.html "$@"

elif [ $1 = "build"  -o $1 = "b" ]; then
  shift
  docker run -it -v $(pwd):/app -w /app node yarn parcel build src/index.html "$@"

elif [ $1 = "i" -o $1 = "install" ]; then
  shift
  docker run -it -v $(pwd):/app -w /app node yarn add "$@"

elif [ $1 = "c" -o $1 = "cmd" ]; then
  shift
  docker run -it -v $(pwd):/app -w /app node bash "$@"

fi
